apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook-dep-sh
  labels:
    app: storybook-sh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storybook-app-sh
  template:
    metadata:
      labels:
        app: storybook-app-sh
    spec:
      containers:
        - name: storybook-sh
          image: REPO_IMAGE
          ports:
            - name: storybook-sh
              containerPort: 6009
