apiVersion: v1
kind: Service
metadata:
  name: storybook-svc-sh
  labels:
    app: storybook-app-sh
spec:
  selector:
    app: storybook-app-sh
  ports:
    - name: storybook-sh
      protocol: TCP
      port: 6009
      targetPort: storybook-sh
